### PR TITLE
Re-add default extensions to PHP 8.0 services

### PR DESCRIPTION
**Pull request by cdubz**
This is a follow up to https://github.com/lando/lando/pull/2717 -- the extensions that were removed as part of that PR all* now support PHP 8.0 and can be re-enabled.

- [apcu](https://pecl.php.net/package/APCu/5.1.19) (5.1.190+)
- [oauth](https://pecl.php.net/package/oauth/2.0.7) (2.0.7)
- [imagick](https://pecl.php.net/package/imagick/3.5.0) (3.5.0+)

\* memcached is little murky. I was able to build and test memcached successfully with PHP 8.0 in my environment but the latest version still only has PHP 8.0 tests but not official support. See https://github.com/php-memcached-dev/php-memcached/issues/466 and e.g. https://github.com/laminas/laminas-cache-storage-adapter-memcached/pull/13, https://github.com/oerdnj/deb.sury.org/issues/1496 (where some packages are moving forward as is). Not sure if there is another option here or if this needs to remain unsupported...

### CODE REVIEW

**Comment by reynoldsalec** [comment]
I think this should be good to merge, going to wait until https://github.com/lando/cli/pull/72 is in.

**Review by reynoldsalec — DISMISSED** [review]

**Comment by cdubz** [comment]
@reynoldsalec with #72 merged the 3.6.0 pre-release out I merged those changes in to this branch just to make sure my changes are still working. Looks like they are locally. Would you like me to test if these same changes can be made to the 8.1 services as well (and update the branch if so)?

**Comment by reynoldsalec** [comment]
That would be awesome @cdubz, thanks for poking me on this, once you get those in let's get 'er merged, we're going to try and do another release in two weeks, so at the latest it should go out then if not sooner.

**Comment by cdubz** [comment]
@reynoldsalec none of the relevant extensions have specifically made a release for PHP 8.1 support (not really surprising) but none of them appear to have any 8.1 issues reported. I was able to use the 3.6.0 pre-release to build an 8.1 container with all four services (apcu, oauth, imagick, memcached) installed and enabled. Imagemagick and memcached appear to work fine in my regular environment (where I use them). I also did some manual testing just using some of the functions provided by oauth and apcu (I don't use either of them normally) and they seem to work fine as well. I think this is good to go 👍

**Pull request merged**
