### PR TITLE
Add support for postgres 14, test 14, 13, 12, 11 and 10

### PR DESCRIPTION
**Pull request by badrange**
Corresponding lando pr:
https://github.com/lando/lando/pull/3221

### CODE REVIEW

**Comment by reynoldsalec** [comment]
@badrange have you tested data persistence between the pinned versions? Just want to make sure if someone has a project using Postgres 13 and they update Lando that they won't lose the database on one of their projects unexpectedly.

**Comment by badrange** [comment]
> @badrange have you tested data persistence between the pinned versions? Just want to make sure if someone has a project using Postgres 13 and they update Lando that they won't lose the database on one of their projects unexpectedly.

I have not tested. If the major version of Postgres changes, I assume the database will stop working. The user would have to to take a backup dump of the database, upgrade and restore for a major upgrade to work.

Is it so that a `lando rebuild` after upgrading lando will upgrade the postgresql default? Then I guess I should not change the default version here.

Which is a bit "sad" for new users if they don't specify 14 by hand. Ideally we'd have one default setting for new projects (which would always be the most recent version) and let the version in use be "pinned" until people do lando destroy/change the version manually. 

I'll update the pr, just a sec

**Comment by badrange** [comment]
@reynoldsalec I tested now: As expected lando rebuild (with only postgres specified) prevented postgresql from starting after my PR, so I let the default stay as 10.

**Comment by reynoldsalec** [comment]
@badrange actually my concern had been updating the pinned version pairs. Running `lando rebuild` would update the pinned version pair, so someone using Postgres 13 would go from `bitnami/postgresql:13.2.0-debian-10-r83` to `bitnami/postgresql:13.5.0-debian-10-r9`. I don't think that _should_ be a big issue, since the volume should persist that stores their DB data and a minor postgres upgrade shouldn't bork things, but I've been surprised in the past.

However, you have a point about the default Postgres version...if someone isn't specifying a postgres version, then a `lando rebuild` changes their version. Here are the steps I took to doublecheck:

1. Vanilla d9 init:

```lando init \
  --source remote \
  --remote-url https://www.drupal.org/download-latest/tar.gz \
  --remote-options="--strip-components 1" \
  --recipe drupal9 \
  --webroot . \
  --name my-first-drupal9-app```

2. Edited Lando file to use default postgres:

```
name: my-first-drupal9-app
recipe: drupal9
config:
  webroot: .
  database: postgres
```

3. `lando start` checked `lando psql --version` to confirm v10 default.

4. Created drupal site connecting to psql

4. Ran `gh pr checkout 68` on the `lando/cli` project (running from source locally), then manually changed the `version` to 14.

5. `lando rebuild -y`

In this case (basically an unexpected Postgres 10 -> 14 upgrade) the service won't start with this error:

```
database_1   | postgresql 19:40:55.99 INFO  ==> ** Starting PostgreSQL **
database_1   | 2021-11-29 19:40:56.075 GMT [39] FATAL:  database files are incompatible with server
database_1   | 2021-11-29 19:40:56.075 GMT [39] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 14.1.
```

@pirog how do we handle these types of updates going forward? @badrange has refactored this PR so it doesn't change the default, but curious how we should be moving defaults up in the future.

**Comment by reynoldsalec** [comment]
I'm going to accept this as is, talking with @pirog I think we regret the idea of default versions and will have it as a goal to remove that in the future.

**Review by reynoldsalec — APPROVED** [review]

**Pull request merged**
